/**
 * Catálogo central de roles y permisos (PBAC + RBAC).
 * Usado por AuthContext, guards de rutas y componentes con feature flags.
 */

export const ROLES = {
  ADMIN: "ADMIN",
  VENDEDOR: "VENDEDOR",
  DEPOSITO: "DEPOSITO",
  COMPRADOR: "COMPRADOR",
  AUDITOR: "AUDITOR",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // Ventas
  VENTA_VIEW: "VENTA_VIEW",
  VENTA_CREATE: "VENTA_CREATE",
  VENTA_REFUND: "VENTA_REFUND",
  FACTURACION_VIEW: "FACTURACION_VIEW",

  // Inventario
  INVENTARIO_VIEW: "INVENTARIO_VIEW",
  INVENTARIO_EDIT: "INVENTARIO_EDIT",
  PRECIOS_UPDATE: "PRECIOS_UPDATE",
  STOCK_ADJUST: "STOCK_ADJUST",

  // Compras
  COMPRA_VIEW: "COMPRA_VIEW",
  COMPRA_CREATE: "COMPRA_CREATE",
  PROVEEDOR_MANAGE: "PROVEEDOR_MANAGE",

  // Gestión
  USER_MANAGE: "USER_MANAGE",
  ROLE_MANAGE: "ROLE_MANAGE",
  REPORTES_VIEW: "REPORTES_VIEW",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Permisos derivados por rol (mock — en producción vendrían del backend). */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS),
  VENDEDOR: [
    PERMISSIONS.VENTA_VIEW,
    PERMISSIONS.VENTA_CREATE,
    PERMISSIONS.FACTURACION_VIEW,
    PERMISSIONS.INVENTARIO_VIEW,
  ],
  DEPOSITO: [
    PERMISSIONS.INVENTARIO_VIEW,
    PERMISSIONS.INVENTARIO_EDIT,
    PERMISSIONS.STOCK_ADJUST,
  ],
  COMPRADOR: [
    PERMISSIONS.COMPRA_VIEW,
    PERMISSIONS.COMPRA_CREATE,
    PERMISSIONS.PROVEEDOR_MANAGE,
    PERMISSIONS.INVENTARIO_VIEW,
  ],
  AUDITOR: [
    PERMISSIONS.VENTA_VIEW,
    PERMISSIONS.FACTURACION_VIEW,
    PERMISSIONS.INVENTARIO_VIEW,
    PERMISSIONS.COMPRA_VIEW,
    PERMISSIONS.REPORTES_VIEW,
  ],
};
